import { NextResponse } from "next/server";
import { renderToBuffer } from "@react-pdf/renderer";
import nodemailer from "nodemailer";
import { ReportPDF } from "@/lib/report-pdf";
import type { InterpretationsData } from "@/lib/interpretations";
import type { QuizResult } from "@/lib/quiz-types";

type RequestBody = {
  email: string;
  identity: { eyebrow: string; label: string; lines: string[] };
  results: QuizResult[];
  interpretations: InterpretationsData;
  traitNames: Record<string, string>;
  quizTitle: string;
};

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as RequestBody;
    const { email, identity, results, interpretations, traitNames, quizTitle } =
      body;

    if (!email || !email.includes("@")) {
      return NextResponse.json(
        { error: "A valid email address is required." },
        { status: 400 },
      );
    }

    if (!results || !identity) {
      return NextResponse.json(
        { error: "Missing report data." },
        { status: 400 },
      );
    }

    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      return NextResponse.json(
        { error: "Email service is not configured." },
        { status: 503 },
      );
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const pdfBuffer = await renderToBuffer(
      ReportPDF({ identity, results, interpretations, traitNames, quizTitle }),
    );

    await transporter.sendMail({
      from: `Trait <${process.env.SMTP_USER}>`,
      to: email,
      subject: `Your ${quizTitle} Personality Report`,
      html: `
        <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px 16px;">
          <h2 style="font-size: 18px; margin-bottom: 8px;">Your personality report is attached</h2>
          <p style="color: #6b7280; font-size: 14px; line-height: 1.6;">
            Hi! Your <strong>${quizTitle}</strong> report is ready. Open the attached PDF to view your full results.
          </p>
          <p style="color: #9ca3af; font-size: 12px; margin-top: 24px;">
            This report was generated by Trait. It is not a medical diagnosis.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: "personality-report.pdf",
          content: pdfBuffer,
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Failed to send report:", error);
    return NextResponse.json(
      { error: "Failed to send report. Please try again." },
      { status: 500 },
    );
  }
}
